Added wrapper with pagination support for room hierarchy endpoint
mautrix/go pull request #100
Opened 2022-10-31 16:35 UTC by mgcm

This addresses issue #91

2022-11-04 23:55 UTC, jacks0n9 approved these changes
This is a nice pr I sure hope tulir will add it...

2022-11-05 14:32 UTC, sumnerevans requested changes

2022-11-05 14:32 UTC, sumnerevans commented on client.go
> +func (cli *Client) Hierarchy(roomID id.RoomID, from string, max_depth int, suggested_only bool, limit int) (resp *RespHierarchy, err error) {
Go variables should be camelCase.

```suggestion
func (cli *Client) Hierarchy(roomID id.RoomID, from string, maxDepth int, suggestedOnly bool, limit int) (resp *RespHierarchy, err error) {
```

2022-11-05 14:32 UTC, sumnerevans commented on responses.go
> +	OriginServerTs int64           `json:"origin_server_ts"`
Generally this has been aliased to `Timestamp` elsewhere in mautrix-go.

```suggestion
	Timestamp int64           `json:"origin_server_ts"`
```

2022-11-05 14:32 UTC, sumnerevans commented on responses.go
> +	Type           string          `json:"type"`
Maybe this needs to be

```suggestion
	Type           event.Type      `json:"type"`
```

but I am not quite sure.

2022-11-05 17:52 UTC, merged